### ISSUE TITLE
add NCWIT blurb to the publicity page

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#17]

**Comment by strubell** [comment]
could add this to "get involved" page?

**Comment by etosch** [comment]
I added this to the publicity page -- maybe we should have a corporate-y part for the get involved page?

I'm not crazy about the layout -- what I really want is to store the articles in the `_publicity` folder and render it like blog posts. Instead of displaying a summary, though, I'd like to show/hide blurbs `onclick`, since presumable in the future we will have some publicity that will link to external sites, rather than blurbs we've written ourselves.

**Comment by etosch** [comment]
I'm done with this for now.
