### ISSUE TITLE
css link color issue

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#24]
![screen shot 2015-11-08 at 8 42 47 pm](https://cloud.githubusercontent.com/assets/508630/11024233/87d716f0-8659-11e5-8ff6-e83aea8c8926.png)

**Comment by etosch** [comment]
The current coloring also masks the "Older Posts" and "Newer Posts" links.

**Comment by strubell** [comment]
haha oops
