### ISSUE TITLE
Header doesn't work on mobile

### ISSUE THREAD

**Issue by strubell** [CSWomenUMass/cswomenumass.github.io#25]
afaict the rest of the site works well on mobile, but not the header.

**Comment by etosch** [comment]
Is the header overlay done with Photoshop or with CSS?

**Comment by strubell** [comment]
With Photoshop, could and should definitely be done with css, at which
point it would be much easier to resolve this issue

**Comment by strubell** [comment]
Ok. FYI I basically have a fix for this (I ported the header to html, just have to add the "responsive" stuff).

**Comment by etosch** [comment]
@strubell : I think we can close this? Looks fine on mobile for me.

**Comment by strubell** [comment]
yes
