### ISSUE TITLE
port remaining blog posts

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#3]
remaining posts to be ported:
- [x] http://umasscswomen.weebly.com/blog/teacher-training-for-technical-skills-workshops
- [x] http://umasscswomen.weebly.com/blog/invited-speaker-valerie-barr
- [x] http://umasscswomen.weebly.com/blog/grace-hopper-celebration-experiences-part-i

All posts need pictures added. All of the pictures should be in the images folder -- I'm just not sure about how layout is managed.

**Comment by strubell** [comment]
Ok, images added to the posts that were there

**Comment by strubell** [comment]
I also added the post about your best paper award ;)

**Comment by etosch** [comment]
omg u r the worst
