### ISSUE TITLE
figure out how to allow posts coming from specific accounts

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#4]
i am assuming this is possible but it may not be.

**Comment by strubell** [comment]
Restricting collaborators on this project seems like the most straightforward way. I'm guessing project teams are a paid account thing

**Comment by etosch** [comment]
So when I was thinking about this last night, I thought maybe we should have the blog posts folder actually be a submodule. Then that repository would only contain the blog posts, and we would have a readme in it to tell people how to write blog posts. I would also put in an install script so they can test out how things look locally, and make sure all the generated files are in the .gitignore. That way, they would _only_ need to write markdown for posts. The workflow would be like this:

1) Fork the blog posts repo.
2) Write your post in markdown.
3) Run the install script to make sure everything looks good.
4) Push your changes.
5) Submit a pull request _with a screen shot of your blog post_.

What do you think?
