### ISSUE TITLE
css work

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#5]
the theme/general visual stuff is still kind of fugly. figure out how to make this nicer.

**Comment by etosch** [comment]
- [x] header fonts are too big
- [x] offset of the body of the page is weird

**Comment by strubell** [comment]
I don't like the link colors, I want them all to be the same regardless of "visited"

**Comment by etosch** [comment]
the body should be the same width as the image in the header -- right now it's smaller and that's making the contents of the page squished.

**Comment by strubell** [comment]
I'll do this one, but I just want to put it here while I think of it: I did some gross hacky inline-css (just alignment + margins) to deal with image alignment in the blog markdown files, but it would be preferable to just make a class for these cases and refer to that.

**Comment by strubell** [comment]
^ apparently you can't assign multiple people to an issue :)

**Comment by etosch** [comment]
Do we want to email the group about this to find out if there is anyone with an aesthetic sense and some web experience who wants to contribute?

**Comment by strubell** [comment]
definitely, we should at least ask

**Comment by etosch** [comment]
I'm going to close this issue, since I'm pretty happy with the css stuff at this point. Obv. we can accept pull requests from people who make any changes we like, but this is no longer blocking the rollout.
