### ISSUE TITLE
main page should show actual blog posts but probably not all of them

### ISSUE THREAD

**Issue by strubell** [CSWomenUMass/cswomenumass.github.io#6]
I haven't been able to figure out how to use Jekyll's pagination stuff: http://jekyllrb.com/docs/pagination/

It seems like I'm not putting the right index.html somewhere, but we should figure it out. It would be nice to have the actual blog posts on the front page... but we don't want all of them there at the same time.

**Comment by strubell** [comment]
ok, figured it out, changes will be pushed into pr #7

**Comment by etosch** [comment]
hm...I don't see this either in my local version, nor online. are you sure you pushed the changes? Also, you're talking about actually displaying the contents of the blog posts, and not just the titles (i.e., not this:
![screen shot 2015-11-01 at 5 17 59 pm](https://cloud.githubusercontent.com/assets/508630/10871714/8ec774b6-80bc-11e5-88e0-4703c6f66ad0.png)
)

**Comment by strubell** [comment]
Haven't pushed the changes yet, struggling with an annoying bug where we
get duplicate "blog" links at the top

**Comment by etosch** [comment]
Ooh, I was getting that when I had cached copies of stuff -- e.g., I 
used to have two "About"s at the top, since I moved the about info from 
about.md to index.md. Cleaning and re-starting the server cleaned it up 
for me.

On 11/1/15 5:19 PM, Emma Strubell wrote:

> Haven't pushed the changes yet, struggling with an annoying bug where we
> get duplicate "blog" links at the top
> 
> On Sun, Nov 1, 2015 at 5:18 PM etosch notifications@github.com wrote:
> 
> > hm...I don't see this either in my local version, nor online. are 
> > you sure
> > you pushed the changes? Also, you're talking about actually 
> > displaying the
> > contents of the blog posts, and not just the titles (i.e., not this:
> > [image: screen shot 2015-11-01 at 5 17 59 pm]
> > 
> > https://cloud.githubusercontent.com/assets/508630/10871714/8ec774b6-80bc-11e5-88e0-4703c6f66ad0.png
> > )
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/CSWomenUMass/cswomenumass.github.io/issues/6#issuecomment-152869730
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/cswomenumass.github.io/issues/6#issuecomment-152869806.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by strubell** [comment]
Ok, pushed

**Comment by strubell** [comment]
See here: https://github.com/CSWomenUMass/cswomenumass.github.io/blob/master/_includes/header.html#L26 don't know why we're still getting big spaces there? Once that it fixed it should be good

**Comment by strubell** [comment]
ok, fixed
