### ISSUE TITLE
twitter icon absurdly large

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cswomenumass.github.io#76]
Firefox 45.0.2.:
![screen shot 2016-04-28 at 9 45 24 am](https://cloud.githubusercontent.com/assets/508630/14887980/0e7dd9a2-0d26-11e6-9a8c-b44301e37d0d.png)

**Comment by strubell** [comment]
lmao who messed with the css, why is this happening

**Comment by strubell** [comment]
we're just _really_ into twitter

**Comment by strubell** [comment]
@etosch I've identified that you caused this :)

**Comment by strubell** [comment]
fixed
