### ISSUE TITLE
Thumbnails on front page

### ISSUE THREAD

**Issue by strubell** [CSWomenUMass/cswomenumass.github.io#8]
would look nice, since we try to have pictures in our blog posts. I expect someone in the world has already gone through the trouble of doing this in Jekyll, we just have to find their "code".

**Comment by etosch** [comment]
I also want to add some front matter for the author. At first I thought we could have bio pages for people, but I'm not entirely sure how we should manage that. Maybe a bios folder within the _posts folder?

**Comment by strubell** [comment]
I think this is an awesome idea

**Comment by strubell** [comment]
each person writes a bio like emma-bio.md then we have a bio layout

**Comment by strubell** [comment]
i think if we added an "author: " to the blog markdown topmatter, we could
read that in the post layout and automatically populate the bio link

**Comment by strubell** [comment]
ooh also their name-bio.md could use topmatter to organize common attributes like website url, path to picture, email (if given)? then i'm picturing we could generate something like the box on the right hand side of my personal website: http://strubell.github.io/ plus the content of the file, aka their actual summary

**Comment by etosch** [comment]
I just tried adding `style="list-style-image: url('{{ post.thumbnail }}');` to the list item tag in blog.html. I added a `thumnail` header to the blog post that points to the path of the image to use as a thumbnail. Not rendering.

**Comment by strubell** [comment]
full path or relative path to img? try full path if its relative

**Comment by strubell** [comment]
you can also look at the generated html in `_site` to see if liquid is actually doing what you want

**Comment by etosch** [comment]
I tried both `/images/<name>` and `images/<name>`

**Comment by etosch** [comment]
@strubell : let me know what you think of the balance on the page. The thumbnails are live.

The last thing I need to do before closing this issue is to add the author bio stuff.

**Comment by strubell** [comment]
Awesome!!

Is it possible for them to go under the heading? I think this would look
better. I can also take a look at stuff later today.

**Comment by etosch** [comment]
Let me know what you think of the balance now -- I think it's much better. FWIW, it looks like you create varabiles in liquid like so:

`{% assign <id> = <expr> %}`

**Comment by etosch** [comment]
Okay, I'm pretty happy with this for now. The authors right now just point to their homepages; I think this is fine for now. We can consider having bio pages in the future, but I feel like that's something we'll want to consider more seriously when we have an active core group of people contributing to the blog.
